### ISSUE TITLE
AttributeError NoneType object has no attribute get

### ISSUE THREAD

**Issue by ibnesayeed** [arxiv-vanity/engrafo-issues#151]
I am not sure why is [this paper](https://arxiv.org/abs/1405.2330) failing to render.

```
172.17.0.1 - - [11/Dec/2017 16:32:48] "GET /html/1405.2330v1 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1632, in finalize_request
    response = self.process_response(response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1856, in process_response
    response = handler(response)
  File "/usr/local/lib/python2.7/dist-packages/flask_debugtoolbar/__init__.py", line 221, in process_response
    panel.process_response(real_request, response)
  File "/app/server/debug_panels.py", line 116, in process_response
    self.arxiv_id = request.view_args.get('arxiv_id')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by bfirsh** [comment]
Ah! Funnily you've actually found a bug in the link on the Arxiv Vanity error. If you add a slash, you'll see the real error. Like so:

http://localhost:8010/html/1405.2330v1/

Looks like the package `fancyvrb` isn't supported, and it's causing lots of errors.

Thanks for investigating!
