### ISSUE TITLE
Problem with Author info (ORCID)

### ISSUE THREAD

**Issue by ax3l** [arxiv-vanity/engrafo-issues#85]
Problem with Author info (manually added ORCID) in `\author`

```latex
\author{Axel Huebl\inst{1,2}(0000-0003-1943-7141)}
```

```bash
docker run  -v "$(pwd)":/workdir -w /workdir arxivvanity/engrafo engrafo -o output/ arxiv/ms.tex
Rendering tex file output/ms.tex
Engrafo rendering failed: Error: pandoc exited with status 65
stdout: 
stderr: 
Error at "source" (line 48, column 29):
unexpected (
expecting \end{document}
\author{Axel Huebl\inst{1,2}(0000-0003-1943-7141)
                            ^

    at ChildProcess.pandoc.on.code (/app/src/index.js:59:9)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Socket.stream.socket.on (internal/child_process.js:348:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:547:12)
```

Arxiv ID: [1706.00522](https://arxiv.org/abs/1706.00522)

https://www.arxiv-vanity.com/papers/1706.00522/

http://localhost:8010/html/1706.00522/

**Comment by ax3l** [comment]
@bfirsh it looks like the switch to LaTeXML in #210 also fixed this issue :) it's rendering now :)

**Comment by bfirsh** [comment]
Hurray!
